//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soort rekening.
        /// </summary>
        internal static string Account_type {
            get {
                return ResourceManager.GetString("Account type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaarlikse beleggingsgeldehersiening.
        /// </summary>
        internal static string Annual_investment_fee_review {
            get {
                return ResourceManager.GetString("Annual investment fee review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As deel van ons jaarlikse prysingshersiening hetsommige van ons gelde verander. Jy kan op dieNedbank-webwerf na ons 2022-prysingsgids gaankyk..
        /// </summary>
        internal static string As_part_of_our_annual_pricing_review__some_of_our_fees_have_changed__You_can_view_our_2022_pricing_guide_on_the_Nedbank_website_ {
            get {
                return ResourceManager.GetString("As part of our annual pricing review, some of our fees have changed. You can view" +
                        " our 2022 pricing guide on the Nedbank website.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outomatiese herbelegging wanneer ubelegging uitkeer.
        /// </summary>
        internal static string Automatic_reinvestment_when_your_investment_matures {
            get {
                return ResourceManager.GetString("Automatic reinvestment when your investment matures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo soos op.
        /// </summary>
        internal static string Balance_at {
            get {
                return ResourceManager.GetString("Balance at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uiteensetting van u beleggingsrekenings.
        /// </summary>
        internal static string Breakdown_of_your_investment_accounts {
            get {
                return ResourceManager.GetString("Breakdown of your investment accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliek vir meer inligting..
        /// </summary>
        internal static string Click_here_for_more_information_ {
            get {
                return ResourceManager.GetString("Click here for more information.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eindsaldo.
        /// </summary>
        internal static string Closing_balance {
            get {
                return ResourceManager.GetString("Closing balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7-kontaksentrum.
        /// </summary>
        internal static string Contact_centre {
            get {
                return ResourceManager.GetString("Contact centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediet.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidige rentekoers.
        /// </summary>
        internal static string Current_interest_rate {
            get {
                return ResourceManager.GetString("Current interest rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidige beleggersaldo.
        /// </summary>
        internal static string Current_investor_balance {
            get {
                return ResourceManager.GetString("Current investor balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geagte.
        /// </summary>
        internal static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debiet.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrywing.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verklarende aantekeninge.
        /// </summary>
        internal static string Explanatory_notes {
            get {
                return ResourceManager.GetString("Explanatory notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaste deposito&apos;s.
        /// </summary>
        internal static string Fixed_deposits {
            get {
                return ResourceManager.GetString("Fixed deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As jy nie op ’n skakel wil klik nie, tik asseblief dievolgende adres in jou blaaier in (sonder die asteriske):.
        /// </summary>
        internal static string If_you_do_not_want_to_click_on_a_link__please_type_the_following_address_in_your_browser__without_the_asterisks__ {
            get {
                return ResourceManager.GetString("If you do not want to click on a link, please type the following address in your " +
                        "browser (without the asterisks):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentebeskikking.
        /// </summary>
        internal static string Interest_disposal {
            get {
                return ResourceManager.GetString("Interest disposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rente verskuldig.
        /// </summary>
        internal static string Interest_due {
            get {
                return ResourceManager.GetString("Interest due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belegging.
        /// </summary>
        internal static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleggingsno.
        /// </summary>
        internal static string Investment_no {
            get {
                return ResourceManager.GetString("Investment no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleggingsportefeuljestaat.
        /// </summary>
        internal static string Investment_portfolio_statement {
            get {
                return ResourceManager.GetString("Investment portfolio statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleggersno.
        /// </summary>
        internal static string Investor_no {
            get {
                return ResourceManager.GetString("Investor no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleggersprestasie.
        /// </summary>
        internal static string Investor_performance {
            get {
                return ResourceManager.GetString("Investor performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervaldatum.
        /// </summary>
        internal static string Maturity_date {
            get {
                return ResourceManager.GetString("Maturity date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedbank Bpk Reg No 1951/000009/06. Gemagtigde finansiële diens- en geregistreerde kredietverskaffer (NCRCP16)..
        /// </summary>
        internal static string Nedbank_Ltd_Reg_No_1951_000009_06__Authorised_financial_services_and_registered_credit_provider__NCRCP16__ {
            get {
                return ResourceManager.GetString("Nedbank Ltd Reg No 1951/000009/06. Authorised financial services and registered c" +
                        "redit provider (NCRCP16).", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennis deposito&apos;s.
        /// </summary>
        internal static string Notice_deposits {
            get {
                return ResourceManager.GetString("Notice deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennistydperk.
        /// </summary>
        internal static string Notice_period {
            get {
                return ResourceManager.GetString("Notice period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginsaldo.
        /// </summary>
        internal static string Opening_balance {
            get {
                return ResourceManager.GetString("Opening balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingsdatum.
        /// </summary>
        internal static string Opening_date {
            get {
                return ResourceManager.GetString("Opening date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienste.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staatdatum.
        /// </summary>
        internal static string Statement_date {
            get {
                return ResourceManager.GetString("Statement date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staatdag.
        /// </summary>
        internal static string Statement_Day {
            get {
                return ResourceManager.GetString("Statement Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staattydperk.
        /// </summary>
        internal static string Statement_Period {
            get {
                return ResourceManager.GetString("Statement Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale saldo van al u vaste rekenings..
        /// </summary>
        internal static string Total_balance_of_all_your_fixed_type_accounts_ {
            get {
                return ResourceManager.GetString("Total balance of all your fixed-type accounts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale saldo van al u gekoppelde rekenings..
        /// </summary>
        internal static string Total_balance_of_all_your_linked_type_accounts_ {
            get {
                return ResourceManager.GetString("Total balance of all your linked-type accounts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale saldo van al u kennisdepositorekenings..
        /// </summary>
        internal static string Total_balance_of_all_your_notice_deposit_accounts_ {
            get {
                return ResourceManager.GetString("Total balance of all your notice deposit accounts.", resourceCulture);
            }
        }
    }
}
