trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- script: |
    npm install
    npm run build
  displayName: 'Build Angular'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
  displayName: 'Build .NET Core'
