//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NIS.AccountMaster")]
    public partial class AccountMasterRecord
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string Currency { get; set; }
        public decimal Balance { get; set; }
        public decimal TotalDeposit { get; set; }
        public Nullable<decimal> TotalSpend { get; set; }
        public Nullable<decimal> ProfitEarned { get; set; }
        public string Indicator { get; set; }
        public Nullable<decimal> FeesPaid { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string TenantCode { get; set; }
    }
}
