//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NIS.Asset")]
    public partial class AssetRecord
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
        public long AssetLibraryId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
    }
}
