//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_CorporateSaverTax
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string CapitalBalance { get; set; }
        public string TenantCode { get; set; }
        public string InvestType { get; set; }
        public string InterestIntruction { get; set; }
        public Nullable<System.DateTime> InvestedDate { get; set; }
        public string CapitalMaster { get; set; }
        public string InterestMaster1 { get; set; }
        public string VatOnFeeMaster1 { get; set; }
        public string AgentFeeStructure1 { get; set; }
        public string AgentFeeStructure2 { get; set; }
        public string InterestMaster2 { get; set; }
        public string TotalCapitalMaster { get; set; }
        public string TotalInterestMaster { get; set; }
        public string TotalAgentFeeMaster { get; set; }
        public string VatOnFeeMaster2 { get; set; }
        public string InterestAgentFeeMaster { get; set; }
    }
}
