//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTypeRecord
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TenantCode { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string HeaderHTML { get; set; }
        public string FooterHTML { get; set; }
    }
}
