//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NIS.Top4IncomeSources")]
    public partial class Top4IncomeSourcesRecord
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> CurrentSpend { get; set; }
        public Nullable<decimal> AverageSpend { get; set; }
        public string TenantCode { get; set; }
    }
}
