//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("NIS.WidgetPageTypeMap")]
    public partial class WidgetPageTypeMap
    {
        public long Id { get; set; }
        public long WidgetId { get; set; }
        public long PageTypeId { get; set; }
        public string TenantCode { get; set; }
        public bool IsDynamicWidget { get; set; }
    }
}
