//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetSetting
    {
        public long Id { get; set; }
        public decimal ImageHeight { get; set; }
        public decimal ImageWidth { get; set; }
        public decimal ImageSize { get; set; }
        public string ImageFileExtension { get; set; }
        public decimal VideoSize { get; set; }
        public string VideoFileExtension { get; set; }
        public string TenantCode { get; set; }
    }
}
