//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_AccountAnalysis
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string InvestmentAmt1 { get; set; }
        public string InvestmentAmt2 { get; set; }
        public string InvestmentAmt3 { get; set; }
        public string InvestmentAmt4 { get; set; }
        public string InvestmentAmt5 { get; set; }
        public string InvestmentAmt6 { get; set; }
        public string InvestmentAmt7 { get; set; }
        public string InvestmentAmt8 { get; set; }
        public string InvestmentAmt9 { get; set; }
        public string InvestmentAmt10 { get; set; }
        public string InvestmentAmt11 { get; set; }
        public string InvestmentAmt12 { get; set; }
        public string PersonalLoanAmt1 { get; set; }
        public string PersonalLoanAmt2 { get; set; }
        public string PersonalLoanAmt3 { get; set; }
        public string PersonalLoanAmt4 { get; set; }
        public string PersonalLoanAmt5 { get; set; }
        public string PersonalLoanAmt6 { get; set; }
        public string PersonalLoanAmt7 { get; set; }
        public string PersonalLoanAmt8 { get; set; }
        public string PersonalLoanAmt9 { get; set; }
        public string PersonalLoanAmt10 { get; set; }
        public string PersonalLoanAmt11 { get; set; }
        public string PersonalLoanAmt12 { get; set; }
        public string HomeLoanAmt1 { get; set; }
        public string HomeLoanAmt2 { get; set; }
        public string HomeLoanAmt3 { get; set; }
        public string HomeLoanAmt4 { get; set; }
        public string HomeLoanAmt5 { get; set; }
        public string HomeLoanAmt6 { get; set; }
        public string HomeLoanAmt7 { get; set; }
        public string HomeLoanAmt8 { get; set; }
        public string HomeLoanAmt9 { get; set; }
        public string HomeLoanAmt10 { get; set; }
        public string HomeLoanAmt11 { get; set; }
        public string HomeLoanAmt12 { get; set; }
        public string Greenbacks1 { get; set; }
        public string Greenbacks2 { get; set; }
        public string Greenbacks3 { get; set; }
        public string Greenbacks4 { get; set; }
        public string Greenbacks5 { get; set; }
        public string Greenbacks6 { get; set; }
        public string Greenbacks7 { get; set; }
        public string Greenbacks8 { get; set; }
        public string Greenbacks9 { get; set; }
        public string Greenbacks10 { get; set; }
        public string Greenbacks11 { get; set; }
        public string Greenbacks12 { get; set; }
        public string TenantCode { get; set; }
    }
}
