//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_AccountSummaryRecord
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string InvestmentAmt { get; set; }
        public string PersonalLoanAmt { get; set; }
        public string HomeLoanAmt { get; set; }
        public string Greenbacks { get; set; }
        public string TenantCode { get; set; }
    }
}
