//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_AgentDetails
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string TaxInvoiceNo { get; set; }
        public string ContactName { get; set; }
        public string EmailAddress { get; set; }
        public string RegNo { get; set; }
        public string VATRegNo { get; set; }
        public string FSPLicenseNo { get; set; }
        public string AgentRef { get; set; }
        public string StatementNo { get; set; }
        public string ContactNo { get; set; }
        public string TenantCode { get; set; }
    }
}
