//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CustomerRewardPointsRedeemed
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string Greenbacks1 { get; set; }
        public string Greenbacks2 { get; set; }
        public string Greenbacks3 { get; set; }
        public string Greenbacks4 { get; set; }
        public string Greenbacks5 { get; set; }
        public string Greenbacks6 { get; set; }
        public string Greenbacks7 { get; set; }
        public string Greenbacks8 { get; set; }
        public string Greenbacks9 { get; set; }
        public string Greenbacks10 { get; set; }
        public string Greenbacks11 { get; set; }
        public string Greenbacks12 { get; set; }
        public string TenantCode { get; set; }
    }
}
