//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CustomerProductWiseRewardPoints
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string InvestmentGreenbacks1 { get; set; }
        public string InvestmentGreenbacks2 { get; set; }
        public string InvestmentGreenbacks3 { get; set; }
        public string InvestmentGreenbacks4 { get; set; }
        public string InvestmentGreenbacks5 { get; set; }
        public string InvestmentGreenbacks6 { get; set; }
        public string InvestmentGreenbacks7 { get; set; }
        public string InvestmentGreenbacks8 { get; set; }
        public string InvestmentGreenbacks9 { get; set; }
        public string InvestmentGreenbacks10 { get; set; }
        public string InvestmentGreenbacks11 { get; set; }
        public string InvestmentGreenbacks12 { get; set; }
        public string PersonalLoanGreenbacks1 { get; set; }
        public string PersonalLoanGreenbacks2 { get; set; }
        public string PersonalLoanGreenbacks3 { get; set; }
        public string PersonalLoanGreenbacks4 { get; set; }
        public string PersonalLoanGreenbacks5 { get; set; }
        public string PersonalLoanGreenbacks6 { get; set; }
        public string PersonalLoanGreenbacks7 { get; set; }
        public string PersonalLoanGreenbacks8 { get; set; }
        public string PersonalLoanGreenbacks9 { get; set; }
        public string PersonalLoanGreenbacks10 { get; set; }
        public string PersonalLoanGreenbacks11 { get; set; }
        public string PersonalLoanGreenbacks12 { get; set; }
        public string HomeLoanGreenbacks1 { get; set; }
        public string HomeLoanGreenbacks2 { get; set; }
        public string HomeLoanGreenbacks3 { get; set; }
        public string HomeLoanGreenbacks4 { get; set; }
        public string HomeLoanGreenbacks5 { get; set; }
        public string HomeLoanGreenbacks6 { get; set; }
        public string HomeLoanGreenbacks7 { get; set; }
        public string HomeLoanGreenbacks8 { get; set; }
        public string HomeLoanGreenbacks9 { get; set; }
        public string HomeLoanGreenbacks10 { get; set; }
        public string HomeLoanGreenbacks11 { get; set; }
        public string HomeLoanGreenbacks12 { get; set; }
        public string TenantCode { get; set; }
    }
}
