//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HomeLoanMasterRecord
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string Currency { get; set; }
        public string LoanAmount { get; set; }
        public string Balance { get; set; }
        public string IntialDue { get; set; }
        public string ArrearStatus { get; set; }
        public string ChargeRate { get; set; }
        public string LoanTerm { get; set; }
        public string SecDescription1 { get; set; }
        public string SecDescription2 { get; set; }
        public string SecDescription3 { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string RegisteredAmount { get; set; }
        public string TenantCode { get; set; }
    }
}
