//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HomeLoanArrears
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string CurrentDue { get; set; }
        public string ARREARS_30 { get; set; }
        public string ARREARS_60 { get; set; }
        public string ARREARS_90 { get; set; }
        public string ARREARS_120 { get; set; }
        public string TenantCode { get; set; }
    }
}
