//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HomeLoanSummaryRecord
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string Annual_Interest { get; set; }
        public string Annual_Insurance { get; set; }
        public string Annual_Service_Fee { get; set; }
        public string Annual_Legal_Costs { get; set; }
        public string Annual_Total_Recvd { get; set; }
        public string Basic_Instalment { get; set; }
        public string Houseowner_Ins { get; set; }
        public string Loan_Protection { get; set; }
        public string Recovery_Fee_Debit { get; set; }
        public string Capital_Redemption { get; set; }
        public string Total_Instalment { get; set; }
        public string Service_Fee { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
        public string TenantCode { get; set; }
    }
}
