//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicWidgetFilterDetail
    {
        public long Id { get; set; }
        public long DynamicWidgetId { get; set; }
        public long FieldId { get; set; }
        public string Operator { get; set; }
        public string ConditionalOperator { get; set; }
        public long Sequence { get; set; }
        public string Value { get; set; }
    }
}
