//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingTrendRecord
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public long CustomerId { get; set; }
        public long BatchId { get; set; }
        public string Month { get; set; }
        public decimal SpendAmount { get; set; }
        public Nullable<decimal> SpendPercentage { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> IncomePercentage { get; set; }
        public string TenantCode { get; set; }
    }
}
