//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleRunHistoryRecord
    {
        public long Id { get; set; }
        public long ScheduleId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TenantCode { get; set; }
        public long StatementId { get; set; }
        public string FilePath { get; set; }
        public long ScheduleLogId { get; set; }
    }
}
