//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleLog
    {
        public long Id { get; set; }
        public long ScheduleId { get; set; }
        public string ScheduleName { get; set; }
        public long BatchId { get; set; }
        public string BatchName { get; set; }
        public int NumberOfRetry { get; set; }
        public string LogFilePath { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Status { get; set; }
        public string TenantCode { get; set; }
    }
}
