//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemActivityHistoryRecord
    {
        public long Id { get; set; }
        public string Module { get; set; }
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public Nullable<long> SubEntityId { get; set; }
        public string SubEntityName { get; set; }
        public string ActionTaken { get; set; }
        public long ActionTakenBy { get; set; }
        public string ActionTakenByUserName { get; set; }
        public System.DateTime ActionTakenDate { get; set; }
        public string TenantCode { get; set; }
    }
}
