//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantRecord
    {
        public int Id { get; set; }
        public string TenantCode { get; set; }
        public string TenantName { get; set; }
        public string TenantDescription { get; set; }
        public string TenantType { get; set; }
        public string TenantImage { get; set; }
        public string TenantDomainName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string SecondaryContactName { get; set; }
        public string SecondaryContactNumber { get; set; }
        public string SecondaryEmailAddress { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string TenantCity { get; set; }
        public string TenantState { get; set; }
        public string TenantCountry { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StorageAccount { get; set; }
        public string AccessToken { get; set; }
        public string ApplicationURL { get; set; }
        public string ApplicationModules { get; set; }
        public string BillingEmailAddress { get; set; }
        public string SecondaryLastName { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastName { get; set; }
        public string BillingContactNumber { get; set; }
        public string PanNumber { get; set; }
        public string ServiceTax { get; set; }
        public Nullable<bool> IsPrimaryTenant { get; set; }
        public string ManageType { get; set; }
        public string ExternalCode { get; set; }
        public string AutheticationMode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string ParentTenantCode { get; set; }
        public bool IsTenantConfigured { get; set; }
    }
}
