//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantConfigurationRecord
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string InputDataSourcePath { get; set; }
        public string OutputHTMLPath { get; set; }
        public string OutputPDFPath { get; set; }
        public string ArchivalPath { get; set; }
        public string AssetPath { get; set; }
        public string TenantCode { get; set; }
        public Nullable<int> ArchivalPeriod { get; set; }
        public string ArchivalPeriodUnit { get; set; }
        public string DateFormat { get; set; }
        public string ApplicationTheme { get; set; }
        public string WidgetThemeSetting { get; set; }
        public string BaseUrlForTransactionData { get; set; }
        public string PreviewStatementFunctionName { get; set; }
        public string GenerateStatementRunNowScheduleFunctionName { get; set; }
        public string GenerateStatementScheduleTimeFunctionName { get; set; }
        public string GenerateHtmlFormatForStatementFunctionName { get; set; }
        public string RetryFailedCustomerStatementApiName { get; set; }
        public string ArchivalProcessApiName { get; set; }
        public string DeploymentType { get; set; }
        public string OutputLocationType { get; set; }
        public string NetworkLocation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
