//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Id { get; set; }
        public long CustomerId { get; set; }
        public long AccountId { get; set; }
        public long BatchId { get; set; }
        public System.DateTime Date { get; set; }
        public string TransactionType { get; set; }
        public string AccountType { get; set; }
        public string Details { get; set; }
        public decimal Amount { get; set; }
    }
}
