//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedbankRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DynamicWidget1
    {
        public long Id { get; set; }
        public string WidgetName { get; set; }
        public string WidgetType { get; set; }
        public long EntityId { get; set; }
        public string Title { get; set; }
        public string ThemeType { get; set; }
        public string ThemeCSS { get; set; }
        public string WidgetSettings { get; set; }
        public string WidgetFilterSettings { get; set; }
        public string Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public long LastUpdatedBy { get; set; }
        public Nullable<long> PublishedBy { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string TenantCode { get; set; }
        public Nullable<long> CloneOfWidgetId { get; set; }
        public string Version { get; set; }
        public string PreviewData { get; set; }
        public string PublishedByName { get; set; }
        public string CreatedByName { get; set; }
        public string EntityName { get; set; }
        public string APIPath { get; set; }
        public string RequestType { get; set; }
        public long PageTypeId { get; set; }
    }
}
