CREATE TABLE [NIS].[Asset]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NULL,
	[FilePath] NVARCHAR(500) NOT NULL,
	[AssetLibraryId] BIGINT  NOT NULL,
	[IsDeleted] BIT NOT NULL
)
