CREATE TABLE [NIS].[Entity]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,
    [CreatedOn]BIGINT NOT NULL,
	[CreatedBy]BIGINT NOT NULL,
	[LastUpdatedOn]DATETIME NOT NULL,
	[LastUpdatedBy]BIGINT NOT NULL,
	[IsActive] BIT NOT NULL,
	[IsDeleted] BIT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL
)
