CREATE TABLE [NIS].[Role]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[IsDeleted] BIT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL
)
