CREATE TABLE [NIS].[TenantContact]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[ContactNumber] NVARCHAR(20) NOT NULL,
	[ContactType] NVARCHAR(50) NOT NULL,
	[EmailAddress] NVARCHAR(50) NOT NULL,	
	[Image] NVARCHAR(MAX),
	[IsActive] BIT NOT NULL,
	[IsDeleted] BIT NOT NULL,
	[IsActivationLinkSent]  BIT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL
)