CREATE TABLE [NIS].[TTD_VendorSubscription]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VenderName NVARCHAR(100) NOT NULL,
	CountOfSubscription BIGINT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL, 
)
