CREATE TABLE [NIS].[TTD_UserSubscriptions]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BatchId BIGINT NOT NULL,
	CustomerId BIGINT NOT NULL,
	CountOfSubscription BIGINT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL, 
)
