CREATE TABLE [NIS].[TTD_SubscriptionMaster]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BatchId BIGINT NOT NULL,
	CustomerId BIGINT NOT NULL,
	CustomerCode NVARCHAR(100) NOT NULL,
	VendorName	NVARCHAR(100) NOT NULL,
	Subscription NVARCHAR(100) NOT NULL,	
	Email	NVARCHAR(100) NOT NULL,
	StartDate DateTime  NULL,	
	EndDate DateTime  NULL,
	[TenantCode] NVARCHAR(50) NOT NULL, 
)
