CREATE TABLE [NIS].[TTD_SubscriptionSummary]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BatchId BIGINT NOT NULL,
	CustomerId BIGINT NOT NULL,
	VendorName	NVARCHAR(250) NOT NULL,	
	Subscription NVARCHAR(250) NOT NULL,	
	Total BIGINT NOT NULL,
	AverageSpend BIGINT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL, 
)
