CREATE TABLE [NIS].[TTD_SubscriptionUsage]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EmployeeID	NVARCHAR(100) NOT NULL,	
	Subscription	NVARCHAR(100) NOT NULL,	
	VendorName	NVARCHAR(100) NOT NULL,	
	EmployeeName	NVARCHAR(100) NOT NULL,	
	Email	NVARCHAR(100) NOT NULL,	
	Usage	BIGINT NOT NULL,
	Emails	BIGINT NOT NULL,
	Meetings BIGINT NOT NULL
)
