CREATE TABLE [NIS].[TTD_DataUsage]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	Month NVARCHAR(100) NOT NULL,	
	Microsoft BIGINT NOT NULL,
	Zoom BIGINT NOT NULL,
	[TenantCode] NVARCHAR(50) NOT NULL, 
)
