//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using nIS.NedBank;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPageTypeMappingViewModel
    {
        public int ProductId { get; set; }
        public int PageTypeId { get; set; }
        public string PageTypeName { get; set; }
        public IList<StatementViewModel> StatementViewModel { get; set; }
    }
}
