//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchMasterRecord
    {
        public long Id { get; set; }
        public string TenantCode { get; set; }
        public string BatchName { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public Nullable<bool> IsExecuted { get; set; }
        public Nullable<bool> IsDataReady { get; set; }
        public Nullable<int> DataExtractionDay { get; set; }
        public Nullable<int> BatchExecutionDayOfMonth { get; set; }
    }
}
