//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageRecord
    {
        public int Id { get; set; }
        public long BatchId { get; set; }
        public long StatementId { get; set; }
        public long PageId { get; set; }
        public long WidgetId { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Image1 { get; set; }
    }
}
