//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_CorporateSaverMaster
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string AgentContactDetails { get; set; }
        public string AgentClientAddress1 { get; set; }
        public string AgentClientAddress2 { get; set; }
        public string AgentClientAddress3 { get; set; }
        public string AgentClientAddress4 { get; set; }
        public string AgentClientAddress5 { get; set; }
        public string AgentClientAddress6 { get; set; }
        public string AgentProfile { get; set; }
        public string BranchCode { get; set; }
        public string CIFNo { get; set; }
        public string ClientCode { get; set; }
        public string RelationshipManager { get; set; }
        public string VATCalculation { get; set; }
        public string ClientVatNo { get; set; }
        public string TaxInvoiceNo { get; set; }
        public string AgentContactPerson { get; set; }
        public string AgentEmailAddress { get; set; }
        public string AgentRegNo { get; set; }
        public string AgentVATRegNo { get; set; }
        public string AgentFSPLicNo { get; set; }
        public string AgentReference { get; set; }
        public string StatementNo { get; set; }
        public string TaxTotalsDescription { get; set; }
        public string TotalInterest { get; set; }
        public string VatOnFee { get; set; }
        public string AgentFeeDeducted { get; set; }
        public string InvestmentDescription { get; set; }
        public string InterestInstruction { get; set; }
        public string InvestmentTotalInterest { get; set; }
        public string AgentFeeStructure1 { get; set; }
        public string AgentFeeStructure2 { get; set; }
        public Nullable<System.DateTime> DateInvested { get; set; }
        public string InvestmentAgentFeeDeducted { get; set; }
        public string InvetsmentVATOnFee { get; set; }
        public string Interest { get; set; }
        public string TenantCode { get; set; }
    }
}
