//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_CorporateSaverTax
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public Nullable<decimal> CapitalBalance { get; set; }
        public string TenantCode { get; set; }
        public string InvestType { get; set; }
        public string InterestIntruction { get; set; }
        public Nullable<System.DateTime> DateInvested { get; set; }
        public string CapitalMstr { get; set; }
        public string AgentFeeDeducted { get; set; }
        public string InterestMstr0 { get; set; }
        public string VatOnFeeMstr { get; set; }
        public string AGENT_FEE_STRUCTURE_1 { get; set; }
        public string AGENT_FEE_STRUCTURE_2 { get; set; }
        public string InterestMstr { get; set; }
        public string TotalCapitalMstr { get; set; }
        public string TotalInterestMstr { get; set; }
        public string TotalAgentFeeMstr { get; set; }
        public string VatOnFeeMstr0 { get; set; }
        public string InterestAgentFeeMstr { get; set; }
        public string InterestDescription { get; set; }
    }
}
