//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_CorporateSaverTransactions
    {
        public long Id { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<long> InvestorId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PaymentDetails { get; set; }
        public string TransactionDescription { get; set; }
        public string Amount { get; set; }
        public string Rate { get; set; }
        public string CapitalBalance { get; set; }
        public string TenantCode { get; set; }
    }
}
