//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_CustomerMaster
    {
        public long Id { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string CustomerId { get; set; }
        public long InvestorId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string AddressLine0 { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string EmailAddress { get; set; }
        public string MaskCellNo { get; set; }
        public string Barcode { get; set; }
        public string TenantCode { get; set; }
        public string Language { get; set; }
        public string Segment { get; set; }
    }
}
