//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_Investment_Source
    {
        public long Id { get; set; }
        public string LANGUAGE_CD { get; set; }
        public string SEG_L1_STR { get; set; }
        public string SEGMENT { get; set; }
        public long INVESTOR_GROUP { get; set; }
        public long INVESTOR_ID { get; set; }
        public string BARCODE { get; set; }
        public string CUSTOMER_ID_TEXT { get; set; }
        public string FIRST_NAME_TEXT { get; set; }
        public string SURNAME_TEXT { get; set; }
        public string DS_INVESTOR_NAME { get; set; }
        public string TITLE_TEXT { get; set; }
        public string ADDR_LINE_0 { get; set; }
        public string ADDR_LINE_1 { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string ADDR_LINE_3 { get; set; }
        public string ADDR_LINE_4 { get; set; }
        public string EMAIL { get; set; }
        public string MASKED_CELL_NO { get; set; }
        public long BRANCH_ID { get; set; }
        public string BRANCH_DESCRIPTION { get; set; }
        public string STREET_ADDR_1 { get; set; }
        public string STREET_ADDR_2 { get; set; }
        public string STREET_ADDR_3 { get; set; }
        public string STREET_ADDR_4 { get; set; }
        public Nullable<long> STREET_CODE { get; set; }
        public string BRANCH_PHONE { get; set; }
        public long INVESTMENT_ID { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PRODUCT_TYPE_AFR { get; set; }
        public long PRODUCT_ID { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string PRODUCT_DESCRIPTION_AFR { get; set; }
        public System.DateTime OPEN_DATE_ID { get; set; }
        public string CURRENT_INT_RATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE_ID { get; set; }
        public long INV_INTEREST_DISPOSAL_ID { get; set; }
        public string INV_INTEREST_DISPOSAL_DESCRIPTION { get; set; }
        public string INV_INTEREST_DISPOSAL_DESCRIPTION_AFR { get; set; }
        public string BONUS_INTEREST { get; set; }
        public string NOTICE_PERIOD { get; set; }
        public string NOTICE_PERIOD_AFR { get; set; }
        public System.DateTime TRAN_DATE_ID { get; set; }
        public long DAY_OF_STATEMENT { get; set; }
        public string TRANSACTION_DESCRIPTION { get; set; }
        public string TRANSACTION_DESCRIPTION_AFR { get; set; }
        public string ACCRUED_INTEREST { get; set; }
        public System.DateTime STATEMENT_DATE { get; set; }
        public string CustCol_4 { get; set; }
        public System.DateTime ARCHIVE_DATE { get; set; }
        public string CustCol_5 { get; set; }
        public string WJXBFS1 { get; set; }
        public string WJXBFS2 { get; set; }
        public string WJXBFS3 { get; set; }
        public string WJXBFS4 { get; set; }
        public string WJXBFS5 { get; set; }
    }
}
