//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_MCAMaster
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public long InvestorId { get; set; }
        public string VatNo { get; set; }
        public Nullable<decimal> OverdraftLimit { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> FreeBalance { get; set; }
        public string StatementNo { get; set; }
        public System.DateTime StatementDate { get; set; }
        public string StatementFrequency { get; set; }
        public string TenantCode { get; set; }
    }
}
