//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_SegmentMaster
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public long SegmentTypeId { get; set; }
    
        public virtual NB_SegmentTypeMaster NB_SegmentTypeMaster { get; set; }
    }
}
