//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_ServiceMessagesAndContacts
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Language { get; set; }
        public string Segment { get; set; }
        public long BatchId { get; set; }
        public long InvestorId { get; set; }
        public string Contact { get; set; }
        public string Servicemsg1 { get; set; }
        public string Servicemsg2 { get; set; }
        public string Servicemsg3 { get; set; }
        public string Servicemsg4 { get; set; }
        public string Servicemsg5 { get; set; }
        public string Servicemsg6 { get; set; }
        public string Servicemsg7 { get; set; }
    }
}
