//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementAnalyticRecord
    {
        public long Id { get; set; }
        public long StatementId { get; set; }
        public long WidgetId { get; set; }
        public string WidgetName { get; set; }
        public long PageId { get; set; }
        public string PageName { get; set; }
        public long CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
    }
}
