//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantConfigurationRecord
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string InputDataSourcePath { get; set; }
        public string OutputHTMLPath { get; set; }
        public string OutputPDFPath { get; set; }
    }
}
