//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTD_MeetingUsage_Old
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long CustomerId { get; set; }
        public string Month { get; set; }
        public long Year { get; set; }
        public long Microsoft { get; set; }
        public long Zoom { get; set; }
        public string TenantCode { get; set; }
    }
}
