//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ScheduleLog
    {
        public long Id { get; set; }
        public string ScheduleName { get; set; }
        public string ProcessingTime { get; set; }
        public string RecordProccessed { get; set; }
        public string Status { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string TenantCode { get; set; }
    }
}
