//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MultiTenantUserAccessMapRecord
    {
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public long AssociatedTenantId { get; set; }
        public string AssociatedTenantCode { get; set; }
        public string AssociatedTenantName { get; set; }
        public string AssociatedTenantType { get; set; }
        public long OtherTenantId { get; set; }
        public string OtherTenantCode { get; set; }
        public string OtherTenantName { get; set; }
        public string OtherTenantType { get; set; }
        public string RoleName { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long LastUpdatedBy { get; set; }
        public string LastUpdatedByUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
