CREATE TABLE [TenantManager].[Tenant] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [TenantCode]             NVARCHAR (MAX) NOT NULL,
    [TenantName]             NVARCHAR (MAX) NOT NULL,
    [TenantDescription]      NVARCHAR (MAX) NULL,
    [TenantType]             NVARCHAR (MAX) NULL,
    [TenantImage]            NVARCHAR (MAX) NULL,
    [TenantDomainName]       NVARCHAR (MAX) NOT NULL,
    [FirstName]              NVARCHAR (MAX) NULL,
    [LastName]               NVARCHAR (MAX) NULL,
    [ContactNumber]          NVARCHAR (MAX) NOT NULL,
    [EmailAddress]           NVARCHAR (MAX) NOT NULL,
    [SecondaryContactName]   NVARCHAR (MAX) NULL,
    [SecondaryContactNumber] NVARCHAR (MAX) NULL,
    [SecondaryEmailAddress]  NVARCHAR (MAX) NULL,
    [AddressLine1]           NVARCHAR (MAX) NULL,
    [AddressLine2]           NVARCHAR (MAX) NULL,
    [TenantCity]             NVARCHAR (MAX) NULL,
    [TenantState]            NVARCHAR (MAX) NULL,
    [TenantCountry]          NVARCHAR (MAX) NULL,
    [PinCode]                NVARCHAR (MAX) NULL,
    [StartDate]              DATE           NULL,
    [EndDate]                DATE           NULL,
    [StorageAccount]         NVARCHAR (MAX) NOT NULL,
    [AccessToken]            NVARCHAR (MAX) NOT NULL,
    [ApplicationURL]         NVARCHAR (MAX) NULL,
    [ApplicationModules]     NVARCHAR (MAX) NULL,
    [BillingEmailAddress]    NVARCHAR (MAX) NULL,
    [SecondaryLastName]      NVARCHAR (MAX) NULL,
    [BillingFirstName]       NVARCHAR (MAX) NULL,
    [BillingLastName]        NVARCHAR (MAX) NULL,
    [BillingContactNumber]   NVARCHAR (MAX) NULL,
    [PanNumber]              NVARCHAR (MAX) NULL,
    [ServiceTax]             NVARCHAR (MAX) NULL,
    [IsPrimaryTenant]        BIT            NULL,
    [ManageType]             NVARCHAR (MAX) NULL,
    [ExternalCode]           NVARCHAR (MAX) NULL,
    [AutheticationMode]      NVARCHAR (MAX) NULL,
    [IsActive]               BIT            CONSTRAINT [DF__Tenant__IsActive__6C190EBB] DEFAULT ((1)) NOT NULL,
    [IsDeleted]              BIT            CONSTRAINT [DF__Tenant__IsDelete__6D0D32F4] DEFAULT ((0)) NOT NULL,
    [ParentTenantCode]       NVARCHAR (MAX) NULL,
    [IsTenantConfigured]     BIT            NOT NULL,
    CONSTRAINT [PK__Tenant__3214EC073F2DE561] PRIMARY KEY CLUSTERED ([Id] ASC)
);


